image: node:12.18.3
stages:
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:android:package:
  stage: build
  image: reactnativecommunity/react-native-android
  only:
    - merge_requests
  script:
    - cd android
    - yarn react-native bundle --entry-file index.js --bundle-output bundle.js
  artifacts:
    paths:
      - ./android/app/build/
      - ./android/app/src/main/assets/
